on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: apacheairflow.azurecr.io
        username: ${{ secrets.acr_apacheairflow_username }}
        password: ${{ secrets.acr_apacheairflow_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t apacheairflow.azurecr.io/aksairflowtest:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push apacheairflow.azurecr.io/aksairflowtest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksairflowtest_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksairflowtestaa14 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksairflowtestaa14`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksairflowtestaa14
        container-registry-url: apacheairflow.azurecr.io
        container-registry-username: ${{ secrets.acr_apacheairflow_username }}
        container-registry-password: ${{ secrets.acr_apacheairflow_password }}
        secret-name: aksairflowtedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksairflowtestaa14
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          apacheairflow.azurecr.io/aksairflowtest:${{ github.sha }}
        imagepullsecrets: |
          aksairflowtedockerauth
